### ISSUE TITLE
Complex AD passwords cause Join-Domain script to fail

### ISSUE THREAD

**Issue by kwwendt** [aws-solutions/edit-in-the-cloud-on-aws#7] opened 2022-03-17 19:48 UTC
**Describe the bug**
Complex AD passwords generated by a password manager cause the Join-Domain.ps1 script to fail.

**To Reproduce**
1. Turn auto-rollback off when launching CF template.
2. Launch template and set AD Password to the following (don't include quotes): "W4xfNXj0FD?byq}zv{]R@}GT6RmAd?"
3. The template will never receive the CFN complete notification and it will timeout after 15 minutes.
4. Retrieve Windows password using your specified Key Pair
5. Login to the instance via RDP using the Windows Administrator login and the Key Pair translated password. [[Reference](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/connecting_to_windows_instance.html)]
6. Open a Powershell terminal as Administrator and execute the Join-Domain.ps1 script manually with the parameters specified in the template.

**Expected behavior**
I'd expect the instance to join to the domain since the password is within the specified guidelines documented in the template
AllowedPattern: (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*

MaxLength: '32'
MinLength: '8'

Performing a regex on the password listed above and the allowed pattern, the password passes.

**Please complete the following information about the solution:**

- [X] Version: v.2.1.1
- [X] Region: eu-west-1
- [X] Was the solution modified from the version published on this repository? No.
- [X] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes.
- [X] Were there any errors in the CloudWatch Logs? No. This occurs on the instance.

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
I connected to the Win-host instance using RDP & Windows Administrator credentials. I manually ran the `Join-Domain.ps1` script with the original parameters specified in the CloudFormation stack. When I first ran this command, I received an error regarding line 22 in the Join-Domain.ps1 script (in this deployment, I changed the DomainName). However, I re-deployed the solution and still hit the same error with the script failing but when I RDP into the instance and manually ran the command with the same password, it succeeds.

**Comment by alcousins** [comment] 2022-03-18 06:03
I'll work on reproducing this and tracing it out.

**Comment by alcousins** [comment] 2022-03-20 23:13
It's powershell not liking the curly braces, in the first instance at least. I am planning to rejig this domain join process in a future version, so i'll look at the options this week. Fixes are potentially:

1) tighten the regex to exclude additional characters as a workaround
2) modify the powershell script to properly delimit this
3) longer term plan to re-work this process

I'm going to prioritize testing (3) to see if that's the shortest path (as it would improve the overall security profile too), but if that looks like it's going to take a long time to realize, i'll probably push a workaround (1) to stop people getting caught by this.

**Comment by alcousins** [comment] 2022-03-21 10:05
I have a fix based on (3) working in my test env. I'll need to do some more testing this week before i can push an update.

**Comment by cassneal** [comment] 2022-09-12 18:25
@alcousins did your fix work? Can you update here?

**Comment by alcousins** [comment] 2022-09-13 01:45
Ah, i neglected to close this. Yes. This has been addressed by re-working the domain join process to use Systems Manager instead of a powershell script in v2.3.0: https://github.com/aws-solutions/edit-in-the-cloud-on-aws/releases/tag/v2.3.0

**Closed as completed** 2022-10-31 19:46 UTC
Labels: bug
